version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka

    depends_on:
      - zookeeper

    ports:
      - "9092:9092"

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  topic-init:
    image: confluentinc/cp-kafka:7.5.0

    depends_on:
      - kafka

    command: >
      bash -c "
      echo 'Waiting for Kafka...' &&
      sleep 25 &&
      kafka-topics --create --if-not-exists --topic match-events --partitions 5 --replication-factor 1 --bootstrap-server kafka:9092 &&
      kafka-topics --create --if-not-exists --topic score-updates --partitions 5 --replication-factor 1 --bootstrap-server kafka:9092 &&
      kafka-topics --create --if-not-exists --topic match-alerts --partitions 1 --replication-factor 1 --bootstrap-server kafka:9092
      "

  producer-app:
    build: ./producer
    container_name: producer-app

    depends_on:
      - topic-init

  consumer-app:
    build: ./consumer
    container_name: consumer-app

    depends_on:
      - topic-init

    ports:
      - "8080:8080"